#####################################
#          Factory Plugin           #
#           by SYN_T3SL4            #
#####################################

########################################
#   Genel Ayarlar / General Settings   #
########################################
Prefix: "&2&lT&c&lF &e» "
PlaceholderSupport: false
Worlds:
  System: false
  List:
    - 'world'
InfoLines:
  Player:
    - "&5            =&b_&5=&b_&5=&b_&5=&b_&2&lT3SL4&c&lFactory&5=&b_&5=&b_&5=&b_&5=&b_"
    - "&7/fabrika top10 &e» &aFabrika sisteminden en çok para kazananları listeler. &7(&4YAKINDA&7)"
    - "&7/fabrika stats &e» &aKurduğun fabrikalardan ne kadar kazandığını ve diğer detayları görüntülersin."
  Official:
    - "&5            =&b_&5=&b_&5=&b_&5=&b_&2&lT3SL4&c&lFactory&5=&b_&5=&b_&5=&b_&5=&b_"
    - "&7/fabrika ver <Oyuncu> <Adet> &e» &aOyuncuya fabrika bloğu verilir."
    - "&7/fabrika sil <Oyuncu> &e» &aOyuncudan fabrika bloğu siler."
    - "&7/fabrika dagit <Adet> &e» &aSunucudaki herkese belirtilen miktar kadar fabrika bloğu verir."
    - "&7/fabrika sorgula <Oyuncu> &e» &aGirilen oyuncunun fabrikalarını gösterir."
    - "&7/fabrika purge &e» &aTüm fabrika bloklarını kaldırır."
    - "&7/fabrika reload &e» &aEklentiyi yeniler."
FactoryItem:
  System:
    Lore: true
    Enchant: true
  Specs:
    ID: "57"
    Name: "&eFabrika"
    Lore:
      - "&7-----------"
      - " "
      - "&eDaha kolay para kazanmak için,"
      - "&efabrikanı yükseltmeyi unutma :))"
      - " "
      - "&7-----------"
    Enchants:
      - "DURABILITY:30"
      - "DIG_SPEED:20"
CheckMenu:
  Title: "&eFabrika Sorgu"
  OwnerLore:
    - "&7-------------"
    - "&eSahibi: &c%player%"
    - "&eFabrika Sayısı: &c%toplamadet%"
    - "&7-------------"
  PlayerLore:
    - "&7-------------"
    - "&eHenüz fabrika satın almamışsınız!"
    - "&7-------------"

########################################
#   Genel Mesajlar / General Messages  #
########################################
Errors:
  CommandErrors:
    GiveCommandERR: "&7/fabrika ver <Oyuncu> <Adet> &e» &aOyuncuya fabrika bloğu verilir."
    DistributeCommandERR: "&7/fabrika dagit <Adet> &e» &aSunucudaki herkese belirtilen miktar kadar fabrika bloğu verir."
    DeleteCommandERR: "&7/fabrika sil <Oyuncu> &e» &aOyuncudan fabrika bloğu siler."
    PurgeCommandERR: "&7/fabrika purge &e» &aTüm fabrika bloklarını kaldırır."
    SorgulaCommandERR: "&7/fabrika sorgula <Oyuncu> &e» &aGirilen oyuncunun fabrikalarını gösterir."
    StatsCommandERR: "&7/fabrika stats &e» &aKurduğun fabrikalardan ne kadar kazandığını ve diğer detayları görüntülersin."
  PermissionError: "&4Maalesef bu komutu kullanmak için yetkiniz yok."
  PlayerNotFound: "&e%player% &4Adlı oyuncu bulunamadı!"
  MustBeNumber: "&c%deger% &eBir sayı olmadığı için komut başarısız oldu."
  WorldError: "&eBulunduğun dünya olan &c%dunya% &eadlı dünyada fabrikalar devre dışı."
  NullFactoryError: "&c%player% &eAdlı oyuncunun hiç fabrikası yok."
  ConsoleError: "&4Konsol bu komutu kullanamaz !"
Success:
  GivenItem: "&d%player% &eAdlı oyuncuya &c%adet% &etane fabrika verildi."
  DistributedItem: "&eSunucudaki herkese &c%adet% &etane fabrika dağıtıldı."
  AddedItem: "&eEnvanterine &c%adet% &etane fabrika eklendi."
  Reload: "&eEklenti başarılı bir şekilde yenilendi."
  Deleted: "&c%player% &eAdlı oyuncunun &d%adet% &efabrikası silindi."
  Purged: "&c%toplamoyuncu% &eOyuncunun toplamda &d%adet% &efabrikası silindi."
########################################
#    MySQL Ayarları / MySQL Settings   #
########################################
MySQL:
  System: false
  Host: hostname
  Port: "3306"
  Database: database
  TableName: t3sl4factory-db
  User: root
  Password: "123"
