#####################################
#          Factory Plugin           #
#           by SYN_T3SL4            #
#####################################

########################################
#   Genel Ayarlar / General Settings   #
########################################
Prefix: "&2&lT&c&lF &e» "
PlaceholderSupport: false
Worlds:
  System: false
  List:
    - 'world'
InfoLines:
  Player:
    - "&5            =&b_&5=&b_&5=&b_&5=&b_&2&lT3SL4&c&lFactory&5=&b_&5=&b_&5=&b_&5=&b_"
    - "&7/fabrika top10 &e» &aFabrika sisteminden en çok para kazananları listeler."
    - "&7/fabrika stats &e» &aKurduğun fabrikalardan ne kadar kazandığını ve diğer detayları görüntülersin."
  Official:
    - "&5            =&b_&5=&b_&5=&b_&5=&b_&2&lT3SL4&c&lFactory&5=&b_&5=&b_&5=&b_&5=&b_"
    - "&7/fabrika ver <Oyuncu> <Adet> &e» &aOyuncuya fabrika bloğu verilir."
    - "&7/fabrika sil <Oyuncu> &e» &aOyuncudan fabrika bloğu siler."
    - "&7/fabrika dagit <Adet> &e» &aSunucudaki herkese belirtilen miktar kadar fabrika bloğu verir."
    - "&7/fabrika sorgula <Oyuncu> &e» &aGirilen oyuncunun fabrikalarını gösterir."
    - "&7/fabrika purge &e» &aTüm fabrika bloklarını kaldırır."
    - "&7/fabrika reload &e» &aEklentiyi yeniler."

########################################
#   Genel Mesajlar / General Messages  #
########################################
########################################
#    MySQL Ayarları / MySQL Settings   #
########################################
MySQL:
  System: false
  Host: hostname
  Port: "3306"
  Database: database
  TableName: madencoin-db
  User: root
  Password: "123"
